/**
 * Generates pre-computed Gast beach weeks (2005–2075) and writes to src/data/beachWeeks.ts
 * Run: pnpm generate
 *
 * Algorithm (from legacy script.js):
 *   epoch: Dec 30, 2005
 *   daysPerSeason: 91
 *   interval: 8
 *   rotation = Math.floor(n / 4 + interval) % 13
 *   startDate = epoch + (n * 91 + rotation * 7) days
 */

import { writeFileSync } from 'fs';
import { resolve } from 'path';

const EPOCH = new Date('2005-12-30T00:00:00-05:00').getTime();
const MS_PER_DAY = 1000 * 60 * 60 * 24;
const DAYS_PER_SEASON = 91;
const INTERVAL = 8;
const START_YEAR = 2005;
const END_YEAR = 2075;

function toISO(ms: number): string {
  return new Date(ms).toISOString().slice(0, 10);
}

function getStart(n: number): number {
  const rotation = Math.floor(n / 4 + INTERVAL) % 13;
  return EPOCH + (n * DAYS_PER_SEASON + rotation * 7) * MS_PER_DAY;
}

interface Entry {
  n: number;
  startMs: number;
  endMs: number;
  isDouble: boolean;
}

// Collect all seasons in range
const entries: Entry[] = [];
for (let n = 0; ; n++) {
  const startMs = getStart(n);
  const year = new Date(startMs).getFullYear();
  if (year < START_YEAR) continue;
  if (year > END_YEAR) break;
  entries.push({ n, startMs, endMs: startMs + 7 * MS_PER_DAY, isDouble: false });
}

// Detect consecutive (double) weeks — adjacent entries exactly 7 days apart
const merged: Entry[] = [];
let i = 0;
while (i < entries.length) {
  const cur = entries[i];
  const next = entries[i + 1];
  if (next && next.startMs === cur.endMs) {
    merged.push({ n: cur.n, startMs: cur.startMs, endMs: next.endMs, isDouble: true });
    i += 2;
  } else {
    merged.push(cur);
    i++;
  }
}

// Validate against known CSV dates for 2026
const expected2026 = ['2026-03-20', '2026-06-19', '2026-09-18', '2026-12-25'];
const actual2026 = merged.filter(e => e.startMs >= new Date('2026-01-01').getTime() && e.startMs < new Date('2027-01-01').getTime()).map(e => toISO(e.startMs));
for (const date of expected2026) {
  if (!actual2026.includes(date)) throw new Error(`Validation failed: expected ${date} in 2026 output`);
}
console.log('✓ 2026 dates validated against CSV');

// Validate double week from CSV: 2036-11-14 and 2036-11-21 should merge
const double2036 = merged.find(e => toISO(e.startMs) === '2036-11-14');
if (!double2036?.isDouble) throw new Error('Validation failed: expected double week starting 2036-11-14');
console.log('✓ Double week 2036 validated');

const lines = merged.map(e =>
  `  { n: ${e.n}, startDate: '${toISO(e.startMs)}', endDate: '${toISO(e.endMs)}', isDouble: ${e.isDouble} },`
);

const output = `// Generated by scripts/generate.ts — do not edit manually
// Run: pnpm generate
import type { BeachWeek } from './types';

const beachWeeks: BeachWeek[] = [
${lines.join('\n')}
];

export default beachWeeks;
`;

writeFileSync(resolve('src/data/beachWeeks.ts'), output);
console.log(`✓ Wrote ${merged.length} entries to src/data/beachWeeks.ts`);
